import { Inter } from "next/font/google";
import "./globals.css";
import { WalletContextProvider } from "@/context/wallet";
import React from "react";
import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <WalletContextProvider>
        <body className={inter.className}>
          <div className='space-bg fixed top-0 -z-50 w-screen h-screen'>
            <canvas id='canvas'></canvas>
          </div>
          <script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script>
          {children}
          <Footer />
        </body>
      </WalletContextProvider>
    </html>
  );
}
